# Generated by Django 5.2.14 on 2026-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_newsletterissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('system', 'Use system setting'), ('light', 'Accessible light'), ('dark', 'Accessible dark'), ('catppuccin-mocha', 'Catppuccin Mocha'), ('tokyo-night', 'Tokyo Night'), ('dracula', 'Dracula'), ('gruvbox-dark', 'Gruvbox Dark'), ('one-dark', 'One Dark'), ('nord', 'Nord'), ('solarized-dark', 'Solarized Dark'), ('rose-pine', 'Rosé Pine'), ('kanagawa', 'Kanagawa')], default='system', max_length=32),
        ),
    ]
