# Generated by Django 5.2.14 on 2026-06-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_userpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='focus_mode',
            field=models.BooleanField(default=False),
        ),
    ]
