# Generated by Django 5.2.14 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_userpreference_focus_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
