# Generated by Django 5.2.14 on 2026-08-14 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_feed_refresh_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('attempted', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('superseded', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='feeds_jobru_name_2aa348_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('name',), name='unique_running_job_run')],
            },
        ),
    ]
