# Generated by Django 5.2.14 on 2026-08-14 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_newsletter_sanitized_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['fetched_at'], name='feeds_artic_fetched_1fb790_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'fetched_at'], name='feeds_artic_feed_id_b67e43_idx'),
        ),
        migrations.AddIndex(
            model_name='articlereadstate',
            index=models.Index(fields=['user', 'is_read', '-updated_at'], name='feeds_artic_user_id_40dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkreadmarker',
            index=models.Index(fields=['user', 'marked_read_at'], name='feeds_bulkr_user_id_19aa54_idx'),
        ),
        migrations.AddIndex(
            model_name='savedarticle',
            index=models.Index(fields=['user', '-saved_at'], name='feeds_saved_user_id_2663b6_idx'),
        ),
    ]
