# Generated by Django 5.2.14 on 2026-08-17 17:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_deliveries(apps, schema_editor):
    """Record what is already known about each existing save's bookmark.

    A previously confirmed save becomes a succeeded delivery. Everything else
    becomes permanently failed rather than queued: those bookmarks were dropped
    under the old code, and silently posting a backlog of them to a live Linkding
    on deploy is not a decision a migration should make. ``deliver_saved_articles
    --requeue-failed`` is the deliberate opt-in.
    """

    SavedArticle = apps.get_model("feeds", "SavedArticle")
    LinkdingDelivery = apps.get_model("feeds", "LinkdingDelivery")
    LinkdingDelivery.objects.bulk_create(
        [
            LinkdingDelivery(
                saved_article_id=saved.id,
                url=saved.url,
                state="succeeded" if saved.linkding_saved else "permanent_failed",
                attempts=1,
                last_attempt_at=saved.updated_at,
                next_attempt_at=None,
                delivered_at=saved.updated_at if saved.linkding_saved else None,
                error_class="" if saved.linkding_saved else "unknown",
                error_message="" if saved.linkding_saved else saved.linkding_error,
            )
            for saved in SavedArticle.objects.all().iterator()
        ],
        batch_size=500,
    )


def drop_deliveries(apps, schema_editor):
    apps.get_model("feeds", "LinkdingDelivery").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0013_api_token_capabilities_and_signed_nonce"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkdingDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("succeeded", "Succeeded"),
                            ("transient_failed", "Transient failure"),
                            ("permanent_failed", "Permanent failure"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("bookmark_id", models.CharField(blank=True, max_length=64)),
                (
                    "error_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_configured", "Not configured"),
                            ("timeout", "Timeout"),
                            ("connection", "Connection error"),
                            ("rate_limited", "Rate limited"),
                            ("server_error", "Remote server error"),
                            ("auth", "Rejected credentials"),
                            ("client_error", "Rejected request"),
                            ("invalid_response", "Unreadable response"),
                            ("url_mismatch", "Bookmark URL mismatch"),
                            ("unexpected", "Unexpected error"),
                            ("unknown", "Unknown (predates delivery tracking)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="feeds.savedarticle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Linkding deliveries",
                "indexes": [
                    models.Index(
                        fields=["state", "next_attempt_at"],
                        name="feeds_linkd_state_291d72_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("delivered_at__isnull", False),
                                ("error_class", ""),
                                ("next_attempt_at__isnull", True),
                                ("state", "succeeded"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("next_attempt_at__isnull", False),
                                ("state", "queued"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("next_attempt_at__isnull", False),
                                ("state", "transient_failed"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("next_attempt_at__isnull", True),
                                ("state", "permanent_failed"),
                            ),
                            _connector="OR",
                        ),
                        name="linkding_delivery_state_fields_agree",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["queued", "succeeded"]),
                            models.Q(("error_class", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="linkding_delivery_failure_is_classified",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_deliveries, drop_deliveries),
    ]
